language: go
go:
    - 1.11.x
    - master
script:
    - if [ -n "$(go fmt ./...)" ]; then  echo "Go code is not formatted, run ''go fmt ./...''" >&2; exit 1;  fi
    - go vet ./...
    - go test ./...
