language: go
matrix:
  fast_finish: true
  include:
  - go: 1.6.x
  - go: 1.7.x
  - go: 1.8.x
  - go: 1.9.x
  - go: 1.10.x
  - go: 1.11.x
  - go: 1.12.x
script:
  - if [ -n "$(go fmt ./...)" ]; then  echo "Go code is not formatted, run ''go fmt ./...''" >&2; exit 1;  fi
  - go vet ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
